### ISSUE TITLE
404 error page, preview page

### ISSUE THREAD

**Issue by BaseMax** [TarunavBA/boo#33]
## 404

There isn't a GitHub Pages site here.

https://tarunavba.github.io/boo

**Comment by TarunavBA** [comment]
Pls createbone

**Comment by TarunavBA** [comment]
One

**Comment by TarunavBA** [comment]
I yave enabled it @BaseMax

**Comment by TarunavBA** [comment]
check now @BaseMax

**Comment by BaseMax** [comment]
Good 😊🙂

**Comment by TarunavBA** [comment]
@BaseMax can you please submit a pull request w.r.t to the wellness of the program?

**Comment by BaseMax** [comment]
Hi, Can I ask your name?

To be honest I not in writing.
"wellness"?
I think I need to know more about the project first.
What do you mean exactly by wellness. do you have any draft

**Comment by TarunavBA** [comment]
Hi @basemax my name is Tarunav,

You can refer to this website to know more about our project or you can
just blindly copy the contents of this website to our project.
The website is 👉
https://blog.pyplane.com/blog/social-network-project-in-django/

~ 🤖
